// ============================================================
// International country → currency → default tax mapping.
// One flat table (195 UN member states + common territories).
// Used by Settings → General to auto-configure new deployments.
// ============================================================

export interface CountryInfo {
  code: string;          // ISO 3166-1 alpha-2
  name: string;
  currency: string;      // ISO 4217
  symbol: string;
  taxRate: number;       // default VAT/GST %
  taxLabel: string;      // "VAT" | "GST" | "Sales Tax" | "Tax"
}

export const COUNTRIES: CountryInfo[] = [
  { code: 'AF', name: 'Afghanistan', currency: 'AFN', symbol: '؋', taxRate: 10, taxLabel: 'VAT' },
  { code: 'AL', name: 'Albania', currency: 'ALL', symbol: 'L', taxRate: 20, taxLabel: 'VAT' },
  { code: 'DZ', name: 'Algeria', currency: 'DZD', symbol: 'د.ج', taxRate: 19, taxLabel: 'VAT' },
  { code: 'AD', name: 'Andorra', currency: 'EUR', symbol: '€', taxRate: 4.5, taxLabel: 'IGI' },
  { code: 'AO', name: 'Angola', currency: 'AOA', symbol: 'Kz', taxRate: 14, taxLabel: 'VAT' },
  { code: 'AG', name: 'Antigua and Barbuda', currency: 'XCD', symbol: 'EC$', taxRate: 15, taxLabel: 'ABST' },
  { code: 'AR', name: 'Argentina', currency: 'ARS', symbol: '$', taxRate: 21, taxLabel: 'IVA' },
  { code: 'AM', name: 'Armenia', currency: 'AMD', symbol: '֏', taxRate: 20, taxLabel: 'VAT' },
  { code: 'AU', name: 'Australia', currency: 'AUD', symbol: 'A$', taxRate: 10, taxLabel: 'GST' },
  { code: 'AT', name: 'Austria', currency: 'EUR', symbol: '€', taxRate: 20, taxLabel: 'VAT' },
  { code: 'AZ', name: 'Azerbaijan', currency: 'AZN', symbol: '₼', taxRate: 18, taxLabel: 'VAT' },
  { code: 'BS', name: 'Bahamas', currency: 'BSD', symbol: 'B$', taxRate: 10, taxLabel: 'VAT' },
  { code: 'BH', name: 'Bahrain', currency: 'BHD', symbol: '.د.ب', taxRate: 10, taxLabel: 'VAT' },
  { code: 'BD', name: 'Bangladesh', currency: 'BDT', symbol: '৳', taxRate: 15, taxLabel: 'VAT' },
  { code: 'BB', name: 'Barbados', currency: 'BBD', symbol: 'Bds$', taxRate: 17.5, taxLabel: 'VAT' },
  { code: 'BY', name: 'Belarus', currency: 'BYN', symbol: 'Br', taxRate: 20, taxLabel: 'VAT' },
  { code: 'BE', name: 'Belgium', currency: 'EUR', symbol: '€', taxRate: 21, taxLabel: 'VAT' },
  { code: 'BZ', name: 'Belize', currency: 'BZD', symbol: 'BZ$', taxRate: 12.5, taxLabel: 'GST' },
  { code: 'BJ', name: 'Benin', currency: 'XOF', symbol: 'CFA', taxRate: 18, taxLabel: 'VAT' },
  { code: 'BT', name: 'Bhutan', currency: 'BTN', symbol: 'Nu.', taxRate: 7, taxLabel: 'Sales Tax' },
  { code: 'BO', name: 'Bolivia', currency: 'BOB', symbol: 'Bs.', taxRate: 13, taxLabel: 'IVA' },
  { code: 'BA', name: 'Bosnia and Herzegovina', currency: 'BAM', symbol: 'KM', taxRate: 17, taxLabel: 'VAT' },
  { code: 'BW', name: 'Botswana', currency: 'BWP', symbol: 'P', taxRate: 14, taxLabel: 'VAT' },
  { code: 'BR', name: 'Brazil', currency: 'BRL', symbol: 'R$', taxRate: 17, taxLabel: 'ICMS' },
  { code: 'BN', name: 'Brunei', currency: 'BND', symbol: 'B$', taxRate: 0, taxLabel: 'Tax' },
  { code: 'BG', name: 'Bulgaria', currency: 'BGN', symbol: 'лв', taxRate: 20, taxLabel: 'VAT' },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF', symbol: 'CFA', taxRate: 18, taxLabel: 'VAT' },
  { code: 'BI', name: 'Burundi', currency: 'BIF', symbol: 'FBu', taxRate: 18, taxLabel: 'VAT' },
  { code: 'KH', name: 'Cambodia', currency: 'KHR', symbol: '៛', taxRate: 10, taxLabel: 'VAT' },
  { code: 'CM', name: 'Cameroon', currency: 'XAF', symbol: 'FCFA', taxRate: 19.25, taxLabel: 'VAT' },
  { code: 'CA', name: 'Canada', currency: 'CAD', symbol: 'C$', taxRate: 5, taxLabel: 'GST' },
  { code: 'CV', name: 'Cape Verde', currency: 'CVE', symbol: '$', taxRate: 15, taxLabel: 'VAT' },
  { code: 'CF', name: 'Central African Republic', currency: 'XAF', symbol: 'FCFA', taxRate: 19, taxLabel: 'VAT' },
  { code: 'TD', name: 'Chad', currency: 'XAF', symbol: 'FCFA', taxRate: 18, taxLabel: 'VAT' },
  { code: 'CL', name: 'Chile', currency: 'CLP', symbol: '$', taxRate: 19, taxLabel: 'IVA' },
  { code: 'CN', name: 'China', currency: 'CNY', symbol: '¥', taxRate: 13, taxLabel: 'VAT' },
  { code: 'CO', name: 'Colombia', currency: 'COP', symbol: '$', taxRate: 19, taxLabel: 'IVA' },
  { code: 'KM', name: 'Comoros', currency: 'KMF', symbol: 'CF', taxRate: 10, taxLabel: 'VAT' },
  { code: 'CG', name: 'Congo', currency: 'XAF', symbol: 'FCFA', taxRate: 18.9, taxLabel: 'VAT' },
  { code: 'CD', name: 'DR Congo', currency: 'CDF', symbol: 'FC', taxRate: 16, taxLabel: 'VAT' },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC', symbol: '₡', taxRate: 13, taxLabel: 'IVA' },
  { code: 'CI', name: "Côte d'Ivoire", currency: 'XOF', symbol: 'CFA', taxRate: 18, taxLabel: 'VAT' },
  { code: 'HR', name: 'Croatia', currency: 'EUR', symbol: '€', taxRate: 25, taxLabel: 'VAT' },
  { code: 'CU', name: 'Cuba', currency: 'CUP', symbol: '$', taxRate: 20, taxLabel: 'Sales Tax' },
  { code: 'CY', name: 'Cyprus', currency: 'EUR', symbol: '€', taxRate: 19, taxLabel: 'VAT' },
  { code: 'CZ', name: 'Czech Republic', currency: 'CZK', symbol: 'Kč', taxRate: 21, taxLabel: 'VAT' },
  { code: 'DK', name: 'Denmark', currency: 'DKK', symbol: 'kr', taxRate: 25, taxLabel: 'VAT' },
  { code: 'DJ', name: 'Djibouti', currency: 'DJF', symbol: 'Fdj', taxRate: 10, taxLabel: 'VAT' },
  { code: 'DM', name: 'Dominica', currency: 'XCD', symbol: 'EC$', taxRate: 15, taxLabel: 'VAT' },
  { code: 'DO', name: 'Dominican Republic', currency: 'DOP', symbol: 'RD$', taxRate: 18, taxLabel: 'ITBIS' },
  { code: 'EC', name: 'Ecuador', currency: 'USD', symbol: '$', taxRate: 15, taxLabel: 'IVA' },
  { code: 'EG', name: 'Egypt', currency: 'EGP', symbol: 'E£', taxRate: 14, taxLabel: 'VAT' },
  { code: 'SV', name: 'El Salvador', currency: 'USD', symbol: '$', taxRate: 13, taxLabel: 'IVA' },
  { code: 'GQ', name: 'Equatorial Guinea', currency: 'XAF', symbol: 'FCFA', taxRate: 15, taxLabel: 'VAT' },
  { code: 'ER', name: 'Eritrea', currency: 'ERN', symbol: 'Nfk', taxRate: 5, taxLabel: 'Sales Tax' },
  { code: 'EE', name: 'Estonia', currency: 'EUR', symbol: '€', taxRate: 22, taxLabel: 'VAT' },
  { code: 'SZ', name: 'Eswatini', currency: 'SZL', symbol: 'L', taxRate: 15, taxLabel: 'VAT' },
  { code: 'ET', name: 'Ethiopia', currency: 'ETB', symbol: 'Br', taxRate: 15, taxLabel: 'VAT' },
  { code: 'FJ', name: 'Fiji', currency: 'FJD', symbol: 'FJ$', taxRate: 15, taxLabel: 'VAT' },
  { code: 'FI', name: 'Finland', currency: 'EUR', symbol: '€', taxRate: 25.5, taxLabel: 'VAT' },
  { code: 'FR', name: 'France', currency: 'EUR', symbol: '€', taxRate: 20, taxLabel: 'TVA' },
  { code: 'GA', name: 'Gabon', currency: 'XAF', symbol: 'FCFA', taxRate: 18, taxLabel: 'VAT' },
  { code: 'GM', name: 'Gambia', currency: 'GMD', symbol: 'D', taxRate: 15, taxLabel: 'VAT' },
  { code: 'GE', name: 'Georgia', currency: 'GEL', symbol: '₾', taxRate: 18, taxLabel: 'VAT' },
  { code: 'DE', name: 'Germany', currency: 'EUR', symbol: '€', taxRate: 19, taxLabel: 'VAT' },
  { code: 'GH', name: 'Ghana', currency: 'GHS', symbol: 'GH₵', taxRate: 15, taxLabel: 'VAT' },
  { code: 'GR', name: 'Greece', currency: 'EUR', symbol: '€', taxRate: 24, taxLabel: 'VAT' },
  { code: 'GD', name: 'Grenada', currency: 'XCD', symbol: 'EC$', taxRate: 15, taxLabel: 'VAT' },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ', symbol: 'Q', taxRate: 12, taxLabel: 'IVA' },
  { code: 'GN', name: 'Guinea', currency: 'GNF', symbol: 'FG', taxRate: 18, taxLabel: 'VAT' },
  { code: 'GW', name: 'Guinea-Bissau', currency: 'XOF', symbol: 'CFA', taxRate: 15, taxLabel: 'VAT' },
  { code: 'GY', name: 'Guyana', currency: 'GYD', symbol: 'G$', taxRate: 14, taxLabel: 'VAT' },
  { code: 'HT', name: 'Haiti', currency: 'HTG', symbol: 'G', taxRate: 10, taxLabel: 'TCA' },
  { code: 'HN', name: 'Honduras', currency: 'HNL', symbol: 'L', taxRate: 15, taxLabel: 'ISV' },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD', symbol: 'HK$', taxRate: 0, taxLabel: 'Tax' },
  { code: 'HU', name: 'Hungary', currency: 'HUF', symbol: 'Ft', taxRate: 27, taxLabel: 'VAT' },
  { code: 'IS', name: 'Iceland', currency: 'ISK', symbol: 'kr', taxRate: 24, taxLabel: 'VAT' },
  { code: 'IN', name: 'India', currency: 'INR', symbol: '₹', taxRate: 18, taxLabel: 'GST' },
  { code: 'ID', name: 'Indonesia', currency: 'IDR', symbol: 'Rp', taxRate: 11, taxLabel: 'PPN' },
  { code: 'IR', name: 'Iran', currency: 'IRR', symbol: '﷼', taxRate: 9, taxLabel: 'VAT' },
  { code: 'IQ', name: 'Iraq', currency: 'IQD', symbol: 'د.ع', taxRate: 15, taxLabel: 'Sales Tax' },
  { code: 'IE', name: 'Ireland', currency: 'EUR', symbol: '€', taxRate: 23, taxLabel: 'VAT' },
  { code: 'IL', name: 'Israel', currency: 'ILS', symbol: '₪', taxRate: 17, taxLabel: 'VAT' },
  { code: 'IT', name: 'Italy', currency: 'EUR', symbol: '€', taxRate: 22, taxLabel: 'IVA' },
  { code: 'JM', name: 'Jamaica', currency: 'JMD', symbol: 'J$', taxRate: 15, taxLabel: 'GCT' },
  { code: 'JP', name: 'Japan', currency: 'JPY', symbol: '¥', taxRate: 10, taxLabel: 'JCT' },
  { code: 'JO', name: 'Jordan', currency: 'JOD', symbol: 'JD', taxRate: 16, taxLabel: 'GST' },
  { code: 'KZ', name: 'Kazakhstan', currency: 'KZT', symbol: '₸', taxRate: 12, taxLabel: 'VAT' },
  { code: 'KE', name: 'Kenya', currency: 'KES', symbol: 'KSh', taxRate: 16, taxLabel: 'VAT' },
  { code: 'KI', name: 'Kiribati', currency: 'AUD', symbol: 'A$', taxRate: 12.5, taxLabel: 'VAT' },
  { code: 'KW', name: 'Kuwait', currency: 'KWD', symbol: 'KD', taxRate: 0, taxLabel: 'Tax' },
  { code: 'KG', name: 'Kyrgyzstan', currency: 'KGS', symbol: 'с', taxRate: 12, taxLabel: 'VAT' },
  { code: 'LA', name: 'Laos', currency: 'LAK', symbol: '₭', taxRate: 10, taxLabel: 'VAT' },
  { code: 'LV', name: 'Latvia', currency: 'EUR', symbol: '€', taxRate: 21, taxLabel: 'VAT' },
  { code: 'LB', name: 'Lebanon', currency: 'LBP', symbol: 'ل.ل', taxRate: 11, taxLabel: 'VAT' },
  { code: 'LS', name: 'Lesotho', currency: 'LSL', symbol: 'L', taxRate: 15, taxLabel: 'VAT' },
  { code: 'LR', name: 'Liberia', currency: 'LRD', symbol: 'L$', taxRate: 10, taxLabel: 'GST' },
  { code: 'LY', name: 'Libya', currency: 'LYD', symbol: 'LD', taxRate: 0, taxLabel: 'Tax' },
  { code: 'LI', name: 'Liechtenstein', currency: 'CHF', symbol: 'CHF', taxRate: 8.1, taxLabel: 'VAT' },
  { code: 'LT', name: 'Lithuania', currency: 'EUR', symbol: '€', taxRate: 21, taxLabel: 'VAT' },
  { code: 'LU', name: 'Luxembourg', currency: 'EUR', symbol: '€', taxRate: 17, taxLabel: 'VAT' },
  { code: 'MO', name: 'Macao', currency: 'MOP', symbol: 'MOP$', taxRate: 0, taxLabel: 'Tax' },
  { code: 'MG', name: 'Madagascar', currency: 'MGA', symbol: 'Ar', taxRate: 20, taxLabel: 'VAT' },
  { code: 'MW', name: 'Malawi', currency: 'MWK', symbol: 'MK', taxRate: 16.5, taxLabel: 'VAT' },
  { code: 'MY', name: 'Malaysia', currency: 'MYR', symbol: 'RM', taxRate: 8, taxLabel: 'SST' },
  { code: 'MV', name: 'Maldives', currency: 'MVR', symbol: 'Rf', taxRate: 8, taxLabel: 'GST' },
  { code: 'ML', name: 'Mali', currency: 'XOF', symbol: 'CFA', taxRate: 18, taxLabel: 'VAT' },
  { code: 'MT', name: 'Malta', currency: 'EUR', symbol: '€', taxRate: 18, taxLabel: 'VAT' },
  { code: 'MH', name: 'Marshall Islands', currency: 'USD', symbol: '$', taxRate: 4, taxLabel: 'Sales Tax' },
  { code: 'MR', name: 'Mauritania', currency: 'MRU', symbol: 'UM', taxRate: 16, taxLabel: 'VAT' },
  { code: 'MU', name: 'Mauritius', currency: 'MUR', symbol: '₨', taxRate: 15, taxLabel: 'VAT' },
  { code: 'MX', name: 'Mexico', currency: 'MXN', symbol: '$', taxRate: 16, taxLabel: 'IVA' },
  { code: 'FM', name: 'Micronesia', currency: 'USD', symbol: '$', taxRate: 5, taxLabel: 'GRT' },
  { code: 'MD', name: 'Moldova', currency: 'MDL', symbol: 'L', taxRate: 20, taxLabel: 'VAT' },
  { code: 'MC', name: 'Monaco', currency: 'EUR', symbol: '€', taxRate: 20, taxLabel: 'VAT' },
  { code: 'MN', name: 'Mongolia', currency: 'MNT', symbol: '₮', taxRate: 10, taxLabel: 'VAT' },
  { code: 'ME', name: 'Montenegro', currency: 'EUR', symbol: '€', taxRate: 21, taxLabel: 'VAT' },
  { code: 'MA', name: 'Morocco', currency: 'MAD', symbol: 'DH', taxRate: 20, taxLabel: 'VAT' },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN', symbol: 'MT', taxRate: 16, taxLabel: 'VAT' },
  { code: 'MM', name: 'Myanmar', currency: 'MMK', symbol: 'K', taxRate: 5, taxLabel: 'CT' },
  { code: 'NA', name: 'Namibia', currency: 'NAD', symbol: 'N$', taxRate: 15, taxLabel: 'VAT' },
  { code: 'NR', name: 'Nauru', currency: 'AUD', symbol: 'A$', taxRate: 0, taxLabel: 'Tax' },
  { code: 'NP', name: 'Nepal', currency: 'NPR', symbol: 'रू', taxRate: 13, taxLabel: 'VAT' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR', symbol: '€', taxRate: 21, taxLabel: 'BTW' },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD', symbol: 'NZ$', taxRate: 15, taxLabel: 'GST' },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO', symbol: 'C$', taxRate: 15, taxLabel: 'IVA' },
  { code: 'NE', name: 'Niger', currency: 'XOF', symbol: 'CFA', taxRate: 19, taxLabel: 'VAT' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN', symbol: '₦', taxRate: 7.5, taxLabel: 'VAT' },
  { code: 'KP', name: 'North Korea', currency: 'KPW', symbol: '₩', taxRate: 0, taxLabel: 'Tax' },
  { code: 'MK', name: 'North Macedonia', currency: 'MKD', symbol: 'ден', taxRate: 18, taxLabel: 'VAT' },
  { code: 'NO', name: 'Norway', currency: 'NOK', symbol: 'kr', taxRate: 25, taxLabel: 'MVA' },
  { code: 'OM', name: 'Oman', currency: 'OMR', symbol: 'OMR', taxRate: 5, taxLabel: 'VAT' },
  { code: 'PK', name: 'Pakistan', currency: 'PKR', symbol: 'Rs.', taxRate: 16, taxLabel: 'GST' },
  { code: 'PW', name: 'Palau', currency: 'USD', symbol: '$', taxRate: 0, taxLabel: 'Tax' },
  { code: 'PS', name: 'Palestine', currency: 'ILS', symbol: '₪', taxRate: 16, taxLabel: 'VAT' },
  { code: 'PA', name: 'Panama', currency: 'PAB', symbol: 'B/.', taxRate: 7, taxLabel: 'ITBMS' },
  { code: 'PG', name: 'Papua New Guinea', currency: 'PGK', symbol: 'K', taxRate: 10, taxLabel: 'GST' },
  { code: 'PY', name: 'Paraguay', currency: 'PYG', symbol: '₲', taxRate: 10, taxLabel: 'IVA' },
  { code: 'PE', name: 'Peru', currency: 'PEN', symbol: 'S/', taxRate: 18, taxLabel: 'IGV' },
  { code: 'PH', name: 'Philippines', currency: 'PHP', symbol: '₱', taxRate: 12, taxLabel: 'VAT' },
  { code: 'PL', name: 'Poland', currency: 'PLN', symbol: 'zł', taxRate: 23, taxLabel: 'VAT' },
  { code: 'PT', name: 'Portugal', currency: 'EUR', symbol: '€', taxRate: 23, taxLabel: 'IVA' },
  { code: 'QA', name: 'Qatar', currency: 'QAR', symbol: 'QR', taxRate: 0, taxLabel: 'Tax' },
  { code: 'RO', name: 'Romania', currency: 'RON', symbol: 'lei', taxRate: 19, taxLabel: 'TVA' },
  { code: 'RU', name: 'Russia', currency: 'RUB', symbol: '₽', taxRate: 20, taxLabel: 'VAT' },
  { code: 'RW', name: 'Rwanda', currency: 'RWF', symbol: 'RF', taxRate: 18, taxLabel: 'VAT' },
  { code: 'KN', name: 'Saint Kitts and Nevis', currency: 'XCD', symbol: 'EC$', taxRate: 17, taxLabel: 'VAT' },
  { code: 'LC', name: 'Saint Lucia', currency: 'XCD', symbol: 'EC$', taxRate: 12.5, taxLabel: 'VAT' },
  { code: 'VC', name: 'Saint Vincent', currency: 'XCD', symbol: 'EC$', taxRate: 16, taxLabel: 'VAT' },
  { code: 'WS', name: 'Samoa', currency: 'WST', symbol: 'WS$', taxRate: 15, taxLabel: 'VAGST' },
  { code: 'SM', name: 'San Marino', currency: 'EUR', symbol: '€', taxRate: 17, taxLabel: 'VAT' },
  { code: 'ST', name: 'São Tomé and Príncipe', currency: 'STN', symbol: 'Db', taxRate: 15, taxLabel: 'VAT' },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', symbol: 'SR', taxRate: 15, taxLabel: 'VAT' },
  { code: 'SN', name: 'Senegal', currency: 'XOF', symbol: 'CFA', taxRate: 18, taxLabel: 'VAT' },
  { code: 'RS', name: 'Serbia', currency: 'RSD', symbol: 'дин', taxRate: 20, taxLabel: 'VAT' },
  { code: 'SC', name: 'Seychelles', currency: 'SCR', symbol: 'SR', taxRate: 15, taxLabel: 'VAT' },
  { code: 'SL', name: 'Sierra Leone', currency: 'SLE', symbol: 'Le', taxRate: 15, taxLabel: 'GST' },
  { code: 'SG', name: 'Singapore', currency: 'SGD', symbol: 'S$', taxRate: 9, taxLabel: 'GST' },
  { code: 'SK', name: 'Slovakia', currency: 'EUR', symbol: '€', taxRate: 23, taxLabel: 'VAT' },
  { code: 'SI', name: 'Slovenia', currency: 'EUR', symbol: '€', taxRate: 22, taxLabel: 'VAT' },
  { code: 'SB', name: 'Solomon Islands', currency: 'SBD', symbol: 'SI$', taxRate: 15, taxLabel: 'GST' },
  { code: 'SO', name: 'Somalia', currency: 'SOS', symbol: 'Sh.So.', taxRate: 10, taxLabel: 'Sales Tax' },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR', symbol: 'R', taxRate: 15, taxLabel: 'VAT' },
  { code: 'KR', name: 'South Korea', currency: 'KRW', symbol: '₩', taxRate: 10, taxLabel: 'VAT' },
  { code: 'SS', name: 'South Sudan', currency: 'SSP', symbol: '£', taxRate: 18, taxLabel: 'Sales Tax' },
  { code: 'ES', name: 'Spain', currency: 'EUR', symbol: '€', taxRate: 21, taxLabel: 'IVA' },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR', symbol: 'Rs', taxRate: 18, taxLabel: 'VAT' },
  { code: 'SD', name: 'Sudan', currency: 'SDG', symbol: 'ج.س', taxRate: 17, taxLabel: 'VAT' },
  { code: 'SR', name: 'Suriname', currency: 'SRD', symbol: 'Sr$', taxRate: 10, taxLabel: 'VAT' },
  { code: 'SE', name: 'Sweden', currency: 'SEK', symbol: 'kr', taxRate: 25, taxLabel: 'MOMS' },
  { code: 'CH', name: 'Switzerland', currency: 'CHF', symbol: 'CHF', taxRate: 8.1, taxLabel: 'VAT' },
  { code: 'SY', name: 'Syria', currency: 'SYP', symbol: '£', taxRate: 5, taxLabel: 'VAT' },
  { code: 'TW', name: 'Taiwan', currency: 'TWD', symbol: 'NT$', taxRate: 5, taxLabel: 'VAT' },
  { code: 'TJ', name: 'Tajikistan', currency: 'TJS', symbol: 'SM', taxRate: 14, taxLabel: 'VAT' },
  { code: 'TZ', name: 'Tanzania', currency: 'TZS', symbol: 'TSh', taxRate: 18, taxLabel: 'VAT' },
  { code: 'TH', name: 'Thailand', currency: 'THB', symbol: '฿', taxRate: 7, taxLabel: 'VAT' },
  { code: 'TL', name: 'Timor-Leste', currency: 'USD', symbol: '$', taxRate: 2.5, taxLabel: 'Sales Tax' },
  { code: 'TG', name: 'Togo', currency: 'XOF', symbol: 'CFA', taxRate: 18, taxLabel: 'VAT' },
  { code: 'TO', name: 'Tonga', currency: 'TOP', symbol: 'T$', taxRate: 15, taxLabel: 'CT' },
  { code: 'TT', name: 'Trinidad and Tobago', currency: 'TTD', symbol: 'TT$', taxRate: 12.5, taxLabel: 'VAT' },
  { code: 'TN', name: 'Tunisia', currency: 'TND', symbol: 'DT', taxRate: 19, taxLabel: 'VAT' },
  { code: 'TR', name: 'Turkey', currency: 'TRY', symbol: '₺', taxRate: 20, taxLabel: 'KDV' },
  { code: 'TM', name: 'Turkmenistan', currency: 'TMT', symbol: 'T', taxRate: 15, taxLabel: 'VAT' },
  { code: 'TV', name: 'Tuvalu', currency: 'AUD', symbol: 'A$', taxRate: 0, taxLabel: 'Tax' },
  { code: 'UG', name: 'Uganda', currency: 'UGX', symbol: 'USh', taxRate: 18, taxLabel: 'VAT' },
  { code: 'UA', name: 'Ukraine', currency: 'UAH', symbol: '₴', taxRate: 20, taxLabel: 'VAT' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED', symbol: 'AED', taxRate: 5, taxLabel: 'VAT' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP', symbol: '£', taxRate: 20, taxLabel: 'VAT' },
  { code: 'US', name: 'United States', currency: 'USD', symbol: '$', taxRate: 0, taxLabel: 'Sales Tax' },
  { code: 'UY', name: 'Uruguay', currency: 'UYU', symbol: '$U', taxRate: 22, taxLabel: 'IVA' },
  { code: 'UZ', name: 'Uzbekistan', currency: 'UZS', symbol: 'сўм', taxRate: 12, taxLabel: 'VAT' },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV', symbol: 'VT', taxRate: 15, taxLabel: 'VAT' },
  { code: 'VA', name: 'Vatican City', currency: 'EUR', symbol: '€', taxRate: 22, taxLabel: 'VAT' },
  { code: 'VE', name: 'Venezuela', currency: 'VES', symbol: 'Bs.S', taxRate: 16, taxLabel: 'IVA' },
  { code: 'VN', name: 'Vietnam', currency: 'VND', symbol: '₫', taxRate: 10, taxLabel: 'VAT' },
  { code: 'YE', name: 'Yemen', currency: 'YER', symbol: '﷼', taxRate: 5, taxLabel: 'GST' },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW', symbol: 'K', taxRate: 16, taxLabel: 'VAT' },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWL', symbol: 'Z$', taxRate: 15, taxLabel: 'VAT' },
];

export function findCountry(code?: string): CountryInfo | undefined {
  if (!code) return undefined;
  return COUNTRIES.find((c) => c.code === code.toUpperCase());
}

/** Get currency symbol from settings (falls back to Rs. for legacy PK deployments). */
export function getCurrencySymbol(settings: { countryCode?: string; currencySymbol?: string } | undefined | null): string {
  if (!settings) return 'Rs.';
  if (settings.currencySymbol) return settings.currencySymbol;
  const c = findCountry(settings.countryCode);
  return c?.symbol || 'Rs.';
}

/** Format money with the configured currency symbol. */
export function fmtMoney(
  amount: number,
  settings: { countryCode?: string; currencySymbol?: string } | undefined | null,
  opts: { decimals?: number } = {},
): string {
  const sym = getCurrencySymbol(settings);
  const decimals = opts.decimals ?? 0;
  const n = Number(amount) || 0;
  return `${sym} ${n.toLocaleString(undefined, { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}`;
}