// Pakistan administrative dataset — Provinces → Districts → Major Cities
// Source: latest available admin data. User can always type free-text for missing entries.

export interface ProvinceData {
  name: string;
  districts: { name: string; cities: string[] }[];
}

export const PK_PROVINCES: ProvinceData[] = [
  {
    name: 'Punjab',
    districts: [
      { name: 'Lahore', cities: ['Lahore', 'Raiwind', 'Shahdara'] },
      { name: 'Kasur', cities: ['Kasur', 'Pattoki', 'Chunian', 'Kot Radha Kishan'] },
      { name: 'Sheikhupura', cities: ['Sheikhupura', 'Muridke', 'Ferozewala', 'Sharaqpur'] },
      { name: 'Nankana Sahib', cities: ['Nankana Sahib', 'Sangla Hill', 'Shahkot'] },
      { name: 'Faisalabad', cities: ['Faisalabad', 'Jaranwala', 'Samundri', 'Tandlianwala', 'Chak Jhumra'] },
      { name: 'Chiniot', cities: ['Chiniot', 'Lalian', 'Bhowana'] },
      { name: 'Jhang', cities: ['Jhang', 'Shorkot', 'Ahmadpur Sial', '18 Hazari'] },
      { name: 'Toba Tek Singh', cities: ['Toba Tek Singh', 'Gojra', 'Kamalia', 'Pir Mahal'] },
      { name: 'Gujranwala', cities: ['Gujranwala', 'Kamoke', 'Wazirabad', 'Nowshera Virkan'] },
      { name: 'Gujrat', cities: ['Gujrat', 'Kharian', 'Sarai Alamgir', 'Jalalpur Jattan'] },
      { name: 'Hafizabad', cities: ['Hafizabad', 'Pindi Bhattian'] },
      { name: 'Mandi Bahauddin', cities: ['Mandi Bahauddin', 'Phalia', 'Malakwal'] },
      { name: 'Narowal', cities: ['Narowal', 'Shakargarh', 'Zafarwal'] },
      { name: 'Sialkot', cities: ['Sialkot', 'Daska', 'Pasrur', 'Sambrial'] },
      { name: 'Rawalpindi', cities: ['Rawalpindi', 'Murree', 'Taxila', 'Wah Cantt', 'Gujar Khan', 'Kahuta', 'Kotli Sattian', 'Kallar Syedan'] },
      { name: 'Attock', cities: ['Attock', 'Hassan Abdal', 'Hazro', 'Fateh Jang', 'Pindi Gheb', 'Jand'] },
      { name: 'Chakwal', cities: ['Chakwal', 'Talagang', 'Kallar Kahar', 'Choa Saidan Shah'] },
      { name: 'Jhelum', cities: ['Jhelum', 'Pind Dadan Khan', 'Sohawa', 'Dina'] },
      { name: 'Sargodha', cities: ['Sargodha', 'Bhalwal', 'Sahiwal (Sargodha)', 'Shahpur', 'Sillanwali', 'Kot Momin'] },
      { name: 'Khushab', cities: ['Khushab', 'Jauharabad', 'Quaidabad', 'Naushera (Khushab)'] },
      { name: 'Mianwali', cities: ['Mianwali', 'Isakhel', 'Piplan'] },
      { name: 'Bhakkar', cities: ['Bhakkar', 'Darya Khan', 'Kallur Kot', 'Mankera'] },
      { name: 'Multan', cities: ['Multan', 'Shujabad', 'Jalalpur Pirwala'] },
      { name: 'Khanewal', cities: ['Khanewal', 'Mian Channu', 'Kabirwala', 'Jahanian'] },
      { name: 'Lodhran', cities: ['Lodhran', 'Dunyapur', 'Kahror Pakka'] },
      { name: 'Vehari', cities: ['Vehari', 'Burewala', 'Mailsi', 'Arifwala'] },
      { name: 'Sahiwal', cities: ['Sahiwal', 'Chichawatni'] },
      { name: 'Okara', cities: ['Okara', 'Depalpur', 'Renala Khurd', 'Hujra Shah Muqeem'] },
      { name: 'Pakpattan', cities: ['Pakpattan', 'Arifwala'] },
      { name: 'Bahawalpur', cities: ['Bahawalpur', 'Ahmadpur East', 'Hasilpur', 'Yazman', 'Khairpur Tamewali'] },
      { name: 'Bahawalnagar', cities: ['Bahawalnagar', 'Chishtian', 'Haroonabad', 'Minchinabad', 'Fort Abbas'] },
      { name: 'Rahim Yar Khan', cities: ['Rahim Yar Khan', 'Sadiqabad', 'Khanpur', 'Liaquatpur'] },
      { name: 'Dera Ghazi Khan', cities: ['Dera Ghazi Khan', 'Taunsa', 'Kot Chutta'] },
      { name: 'Rajanpur', cities: ['Rajanpur', 'Jampur', 'Rojhan'] },
      { name: 'Layyah', cities: ['Layyah', 'Karor Lal Esan', 'Chaubara'] },
      { name: 'Muzaffargarh', cities: ['Muzaffargarh', 'Kot Addu', 'Alipur', 'Jatoi'] },
    ],
  },
  {
    name: 'Sindh',
    districts: [
      { name: 'Karachi Central', cities: ['Karachi Central'] },
      { name: 'Karachi East', cities: ['Karachi East'] },
      { name: 'Karachi South', cities: ['Karachi South'] },
      { name: 'Karachi West', cities: ['Karachi West'] },
      { name: 'Karachi Malir', cities: ['Karachi Malir'] },
      { name: 'Karachi Korangi', cities: ['Karachi Korangi'] },
      { name: 'Karachi Keamari', cities: ['Karachi Keamari'] },
      { name: 'Hyderabad', cities: ['Hyderabad', 'Kotri', 'Latifabad'] },
      { name: 'Jamshoro', cities: ['Jamshoro', 'Sehwan', 'Kotri'] },
      { name: 'Dadu', cities: ['Dadu', 'Khairpur Nathan Shah', 'Mehar'] },
      { name: 'Matiari', cities: ['Matiari', 'Hala', 'Saeedabad'] },
      { name: 'Tando Allahyar', cities: ['Tando Allahyar', 'Chamber'] },
      { name: 'Tando Muhammad Khan', cities: ['Tando Muhammad Khan', 'Bulri Shah Karim'] },
      { name: 'Thatta', cities: ['Thatta', 'Makli', 'Mirpur Sakro'] },
      { name: 'Sujawal', cities: ['Sujawal', 'Mirpur Bathoro', 'Jati'] },
      { name: 'Badin', cities: ['Badin', 'Talhar', 'Matli', 'Tando Bago'] },
      { name: 'Mirpur Khas', cities: ['Mirpur Khas', 'Digri', 'Jhuddo'] },
      { name: 'Umerkot', cities: ['Umerkot', 'Kunri', 'Pithoro'] },
      { name: 'Tharparkar', cities: ['Mithi', 'Islamkot', 'Chachro', 'Diplo', 'Nagarparkar'] },
      { name: 'Sanghar', cities: ['Sanghar', 'Tando Adam', 'Shahdadpur', 'Sinjhoro'] },
      { name: 'Nawabshah', cities: ['Nawabshah', 'Sakrand', 'Daur'] },
      { name: 'Naushahro Feroze', cities: ['Naushahro Feroze', 'Moro', 'Bhiria'] },
      { name: 'Sukkur', cities: ['Sukkur', 'Rohri', 'New Sukkur'] },
      { name: 'Khairpur', cities: ['Khairpur', 'Gambat', 'Kingri'] },
      { name: 'Ghotki', cities: ['Ghotki', 'Mirpur Mathelo', 'Daharki', 'Ubauro'] },
      { name: 'Larkana', cities: ['Larkana', 'Ratodero', 'Dokri'] },
      { name: 'Shikarpur', cities: ['Shikarpur', 'Garhi Yasin', 'Khanpur'] },
      { name: 'Jacobabad', cities: ['Jacobabad', 'Thul', 'Garhi Khairo'] },
      { name: 'Kashmore', cities: ['Kashmore', 'Kandhkot', 'Tangwani'] },
      { name: 'Qambar Shahdadkot', cities: ['Qambar', 'Shahdadkot', 'Warah', 'Miro Khan'] },
    ],
  },
  {
    name: 'Khyber Pakhtunkhwa',
    districts: [
      { name: 'Peshawar', cities: ['Peshawar', 'Pabbi'] },
      { name: 'Charsadda', cities: ['Charsadda', 'Shabqadar', 'Tangi'] },
      { name: 'Mardan', cities: ['Mardan', 'Takht Bhai', 'Katlang'] },
      { name: 'Nowshera', cities: ['Nowshera', 'Risalpur', 'Akora Khattak'] },
      { name: 'Swabi', cities: ['Swabi', 'Lahor', 'Topi'] },
      { name: 'Abbottabad', cities: ['Abbottabad', 'Havelian', 'Nawanshehr'] },
      { name: 'Haripur', cities: ['Haripur', 'Khanpur', 'Ghazi'] },
      { name: 'Mansehra', cities: ['Mansehra', 'Balakot', 'Oghi'] },
      { name: 'Battagram', cities: ['Battagram', 'Allai'] },
      { name: 'Torghar', cities: ['Judba'] },
      { name: 'Kohistan', cities: ['Dasu', 'Pattan'] },
      { name: 'Swat', cities: ['Mingora', 'Saidu Sharif', 'Khwazakhela', 'Matta', 'Kabal'] },
      { name: 'Shangla', cities: ['Alpuri', 'Besham', 'Puran'] },
      { name: 'Buner', cities: ['Daggar', 'Khadukhel'] },
      { name: 'Lower Dir', cities: ['Timergara', 'Adenzai', 'Samar Bagh'] },
      { name: 'Upper Dir', cities: ['Dir', 'Sharingal', 'Wari'] },
      { name: 'Chitral', cities: ['Chitral', 'Drosh', 'Booni'] },
      { name: 'Malakand', cities: ['Batkhela', 'Dargai', 'Sakhakot'] },
      { name: 'Kohat', cities: ['Kohat', 'Lachi', 'Gumbat'] },
      { name: 'Hangu', cities: ['Hangu', 'Thall'] },
      { name: 'Karak', cities: ['Karak', 'Banda Daud Shah', 'Takht-e-Nasrati'] },
      { name: 'Bannu', cities: ['Bannu', 'Domel'] },
      { name: 'Lakki Marwat', cities: ['Lakki Marwat', 'Naurang'] },
      { name: 'Dera Ismail Khan', cities: ['Dera Ismail Khan', 'Kulachi', 'Paharpur', 'Daraban'] },
      { name: 'Tank', cities: ['Tank', 'Jandola'] },
      { name: 'Khyber', cities: ['Jamrud', 'Landi Kotal', 'Bara'] },
      { name: 'Mohmand', cities: ['Ghalanai', 'Yakka Ghund'] },
      { name: 'Bajaur', cities: ['Khar', 'Nawagai'] },
      { name: 'Kurram', cities: ['Parachinar', 'Sadda'] },
      { name: 'Orakzai', cities: ['Kalaya', 'Ghiljo'] },
      { name: 'North Waziristan', cities: ['Miranshah', 'Mir Ali'] },
      { name: 'South Waziristan', cities: ['Wana', 'Ladha', 'Sarwakai'] },
    ],
  },
  {
    name: 'Balochistan',
    districts: [
      { name: 'Quetta', cities: ['Quetta', 'Hanna'] },
      { name: 'Pishin', cities: ['Pishin', 'Karezat', 'Barshore'] },
      { name: 'Killa Abdullah', cities: ['Chaman', 'Killa Abdullah', 'Gulistan'] },
      { name: 'Chagai', cities: ['Dalbandin', 'Nokundi', 'Taftan'] },
      { name: 'Nushki', cities: ['Nushki'] },
      { name: 'Mastung', cities: ['Mastung', 'Dasht', 'Kardgap'] },
      { name: 'Kalat', cities: ['Kalat', 'Mangchar', 'Surab'] },
      { name: 'Khuzdar', cities: ['Khuzdar', 'Wadh', 'Nal'] },
      { name: 'Lasbela', cities: ['Uthal', 'Hub', 'Bela', 'Gadani'] },
      { name: 'Awaran', cities: ['Awaran', 'Jhal Jhao'] },
      { name: 'Kech', cities: ['Turbat', 'Buleda', 'Tump'] },
      { name: 'Gwadar', cities: ['Gwadar', 'Pasni', 'Jiwani', 'Ormara'] },
      { name: 'Panjgur', cities: ['Panjgur', 'Gichk'] },
      { name: 'Washuk', cities: ['Washuk', 'Mashkel', 'Basima'] },
      { name: 'Kharan', cities: ['Kharan'] },
      { name: 'Sibi', cities: ['Sibi', 'Lehri', 'Talli'] },
      { name: 'Harnai', cities: ['Harnai'] },
      { name: 'Ziarat', cities: ['Ziarat', 'Sanjavi'] },
      { name: 'Kohlu', cities: ['Kohlu', 'Mawand'] },
      { name: 'Dera Bugti', cities: ['Dera Bugti', 'Sui', 'Phelawagh'] },
      { name: 'Loralai', cities: ['Loralai', 'Duki'] },
      { name: 'Musakhel', cities: ['Musakhel Bazar', 'Kingri'] },
      { name: 'Barkhan', cities: ['Barkhan'] },
      { name: 'Zhob', cities: ['Zhob', 'Qamar Din Karez'] },
      { name: 'Sherani', cities: ['Sherani'] },
      { name: 'Killa Saifullah', cities: ['Killa Saifullah', 'Muslim Bagh'] },
      { name: 'Naseerabad', cities: ['Dera Murad Jamali', 'Tamboo'] },
      { name: 'Jaffarabad', cities: ['Dera Allah Yar', 'Usta Muhammad'] },
      { name: 'Jhal Magsi', cities: ['Gandawah', 'Mirpur'] },
      { name: 'Sohbatpur', cities: ['Sohbatpur'] },
      { name: 'Kachhi (Bolan)', cities: ['Dhadar', 'Bhag', 'Mach'] },
    ],
  },
  {
    name: 'Islamabad Capital Territory',
    districts: [
      { name: 'Islamabad', cities: ['Islamabad', 'Bara Kahu', 'Bhara Kahu', 'Tarnol', 'Nilore'] },
    ],
  },
  {
    name: 'Azad Jammu & Kashmir',
    districts: [
      { name: 'Muzaffarabad', cities: ['Muzaffarabad', 'Patika', 'Chikar'] },
      { name: 'Hattian Bala', cities: ['Hattian Bala', 'Chinari'] },
      { name: 'Neelum', cities: ['Athmuqam', 'Sharda', 'Kel'] },
      { name: 'Mirpur', cities: ['Mirpur', 'Dadyal', 'Chakswari'] },
      { name: 'Bhimber', cities: ['Bhimber', 'Samahni', 'Barnala'] },
      { name: 'Kotli', cities: ['Kotli', 'Sehnsa', 'Khuiratta'] },
      { name: 'Poonch', cities: ['Rawalakot', 'Hajira', 'Thorar'] },
      { name: 'Sudhanoti', cities: ['Pallandri', 'Trarkhel'] },
      { name: 'Bagh', cities: ['Bagh', 'Dhirkot', 'Harigel'] },
      { name: 'Haveli', cities: ['Forward Kahuta', 'Khurshidabad'] },
    ],
  },
  {
    name: 'Gilgit-Baltistan',
    districts: [
      { name: 'Gilgit', cities: ['Gilgit', 'Danyore'] },
      { name: 'Hunza', cities: ['Karimabad', 'Aliabad', 'Gulmit'] },
      { name: 'Nagar', cities: ['Nagar', 'Sumayar'] },
      { name: 'Ghizer', cities: ['Gahkuch', 'Gupis', 'Yasin'] },
      { name: 'Skardu', cities: ['Skardu', 'Shigar'] },
      { name: 'Shigar', cities: ['Shigar'] },
      { name: 'Kharmang', cities: ['Tolti', 'Kharmang'] },
      { name: 'Ghanche', cities: ['Khaplu', 'Daghoni'] },
      { name: 'Astore', cities: ['Astore', 'Eidgah'] },
      { name: 'Diamer', cities: ['Chilas', 'Darel', 'Tangir'] },
    ],
  },
];

export function getProvinces(): string[] {
  return PK_PROVINCES.map(p => p.name);
}

export function getDistricts(province: string): string[] {
  return PK_PROVINCES.find(p => p.name === province)?.districts.map(d => d.name) || [];
}

export function getCities(province: string, district: string): string[] {
  return PK_PROVINCES.find(p => p.name === province)?.districts.find(d => d.name === district)?.cities || [];
}
