import { AppData } from './types';

export function seedData(): AppData {
  return {
    orderCounter: 1000,
    settings: {
      name: '',
      address: '',
      phone1: '',
      phone2: '',
      marketingFooter: 'DIGITAL TARGET SOFTWARE SOLUTIONS\nDeveloped By: Taimoor Younas\n📞 0345-1873354',
      whatsappTemplates: [
        {
          id: 'paid-default',
          name: 'Paid / Bill Clear',
          body: 'Dear {customer_name},\nYour bill/order #{order_number} has been successfully paid.\n\nTotal Amount: Rs. {grand_total}\nThank you for visiting {restaurant_name}.',
        },
        {
          id: 'delivery-default',
          name: 'Delivery Status',
          body: 'Dear {customer_name},\nYour order #{order_number} {delivery_status_line}\n\n{rider_block}\nRestaurant: {restaurant_name}\nThank you!',
        },
      ],
      defaultPaidWhatsAppTemplateId: 'paid-default',
      defaultDeliveryWhatsAppTemplateId: 'delivery-default',
      logo: '',
      logoWidth: 60,
      logoHeight: 60,
      receiptFooter: 'Thank you for dining with us!\nVisit again soon!',
      taxAmount: 0,
      serviceChargePercent: 0,
      qrMode: 'auto',
      customQrImage: '',
      bankName: '',
      urduFont: 'none',
      paperSize: '80mm',
      receiptSizePreset: 'standard-80',
      receiptMode: 'continuous',
      printerDriverType: 'escpos',
      disableExtraFeed: true,
      autoCut: true,
      cutMode: 'full',
      receiptTrimMm: 3,
      silentPrint: true,
      kotEnabled: true,
      autoPrintKot: true,
      autoKitchenPrint: true,
      manualSendToKitchen: false,
      kotFallbackToReceipt: true,
      kitchenPreparingMinutes: 5,
      kitchenWarningMinutes: 10,
    },
    categories: [],
    menuItems: [],
    orders: [],
    floors: [],
    kitchens: [],
    tables: [],
    waiters: [],
    riders: [],
    // OFFLINE BUILD — default admin user seeded.
    // Login: username = admin, password = admin123
    // Admin baki users andar se khud bana lega.
    users: [
      {
        id: 'admin-default',
        name: 'Administrator',
        username: 'admin',
        password: 'admin123',
        role: 'admin',
        isActive: true,
      } as any,
    ],
    inventory: [],
    stockLogs: [],
    employees: [],
    attendance: [],
    leaves: [],
    payslips: [],
    advances: [],
    accountCategories: [
      { id: 'ac1', name: 'Sales', type: 'income' },
      { id: 'ac2', name: 'Other Income', type: 'income' },
      { id: 'ac3', name: 'Rent', type: 'expense' },
      { id: 'ac4', name: 'Utilities', type: 'expense' },
      { id: 'ac5', name: 'Salaries', type: 'expense' },
      { id: 'ac6', name: 'Raw Material', type: 'expense' },
      { id: 'ac7', name: 'Maintenance', type: 'expense' },
      { id: 'ac8', name: 'Misc', type: 'expense' },
    ],
    transactions: [],
    parties: [],
    ledger: [],
    dailyCashCloses: [],
    receivingEntries: [],
    marketingContacts: [],
    recipes: [],
    wastages: [],
    customers: [],
    branches: [],
    creditPayments: [],
    promoCodes: [],
    paymentAccounts: [],
    deals: [],
  } as any;
}
