// ============================================================
// MODERN THEMES — thirteen complete looks for the Modern interface style.
//
// A theme is more than an accent colour: it is a surface tint (page, panels,
// borders), an accent, the colour of the text that sits on the accent, the
// colour the accent takes when it is used AS text on a light surface, and
// whether the sidebar is light or dark. The names are food colours because
// that is what a restaurant recognises: pizza red, burger orange, salad green,
// lemon yellow, milk white, coffee brown …
//
// PRESENTATION ONLY. Choosing a theme sets one attribute and a handful of CSS
// variables on <html> (see applyUiStyle in uiStyle.ts) and stores one
// device-local preference. The surface colours themselves live in
// src/styles/ui-tokens.css, keyed by data-ui-theme, so nothing here can reach
// the database, the licence, users, orders, printers or the print window.
//
// The `surface` triplets below are the SAME values as the CSS blocks — a test
// (src/test/ui-themes.test.ts) reads the stylesheet and fails if they drift,
// and checks that every text/background pair is readable.
// ============================================================
import type { Hsl } from './uiStyle';

export type SidebarStyle = 'light' | 'dark';

/** "h s% l%" — the shape the CSS variables use, so it can be dropped straight into hsl(). */
export type Triplet = string;

export interface ThemeSurface {
  /** The page behind the panels. */
  background: Triplet;
  /** Panels and cards (white when absent; a dark theme sets its own). */
  card?: Triplet;
  /** Body text. */
  foreground: Triplet;
  /** Quiet text: captions, hints. */
  mutedForeground: Triplet;
  /** Subtle fills: table header, chips. */
  muted: Triplet;
  border: Triplet;
}

export interface UiTheme {
  id: string;
  name: string;
  /** One line for the gallery. */
  tagline: string;
  /** Buttons, selection, highlights. Exact — themes are hand-tuned, not auto-darkened. */
  accent: Hsl;
  /** Colour of text and icons that sit on the accent. */
  onAccent: 'light' | 'dark';
  /** The accent used as TEXT on a light surface (prices, links, active labels). Defaults to the accent. */
  accentText?: Hsl;
  surface: ThemeSurface;
  sidebar: SidebarStyle;
  /** The sidebar colour when it is dark (also used by the gallery preview). */
  sidebarColor?: Triplet;
  /** 'retail' marks the DT Retail family (gradient sidebar, hero banner, motion). Absent = a plain Modern theme. */
  family?: 'retail';
  /** The whole page is dark (Night, Black & Gold), not just the sidebar. */
  dark?: boolean;
  /** Top and bottom of the retail sidebar gradient. */
  sidebarGradient?: [Triplet, Triplet];
  /** Start and end of the retail hero banner / highlighted KPI gradient. */
  hero?: [Triplet, Triplet];
  /** Four chips shown in the gallery: sidebar, accent, page, highlight. */
  swatches?: [string, string, string, string];
  /** A theme designed in Settings → Custom: its stylesheet block, generated by lib/customTheme.ts (built-in themes use ui-tokens.css). */
  css?: string;
  /** True for a theme made in Settings → Custom (or imported from a theme file). */
  custom?: boolean;
}

/** Near-black used for text on a light accent (yellow). */
export const INK_ON_ACCENT: Triplet = '28 45% 9%';
export const WHITE: Triplet = '0 0% 100%';

export const UI_THEMES: UiTheme[] = [
  {
    id: 'ember',
    name: 'Ember Orange',
    tagline: 'Warm and appetising. The default.',
    accent: { h: 16, s: 88, l: 44 },
    onAccent: 'light',
    accentText: { h: 16, s: 88, l: 41 }, // a shade deeper where the accent is text on the cream page
    surface: { background: '40 18% 96%', foreground: '24 15% 11%', mutedForeground: '25 8% 40%', muted: '36 14% 94%', border: '35 14% 89%' },
    sidebar: 'light',
  },
  {
    id: 'tomato',
    name: 'Tomato Red',
    tagline: 'Bold pizza-menu red on clean white.',
    accent: { h: 356, s: 78, l: 45 },
    onAccent: 'light',
    surface: { background: '24 12% 96%', foreground: '12 14% 10%', mutedForeground: '14 7% 40%', muted: '20 9% 93%', border: '20 9% 88%' },
    sidebar: 'light',
  },
  {
    id: 'pizza',
    name: 'Red & Yellow',
    tagline: 'Fast-food brand look: red actions, yellow highlights, cream plates.',
    accent: { h: 357, s: 82, l: 46 },
    onAccent: 'light',
    surface: { background: '220 16% 96%', foreground: '0 0% 9%', mutedForeground: '220 6% 40%', muted: '220 12% 94%', border: '220 12% 90%' },
    sidebar: 'light',
  },
  {
    id: 'fresh',
    name: 'Fresh Green',
    tagline: 'Salad-bar green with a mint-white page.',
    accent: { h: 152, s: 62, l: 30 },
    onAccent: 'light',
    surface: { background: '148 24% 96%', foreground: '160 22% 9%', mutedForeground: '158 8% 38%', muted: '148 15% 93%', border: '148 13% 86%' },
    sidebar: 'light',
  },
  {
    id: 'sunny',
    name: 'Sunny Yellow',
    tagline: 'Lemon and cheese yellow with dark, easy-to-read text.',
    accent: { h: 44, s: 97, l: 52 },
    onAccent: 'dark',
    accentText: { h: 34, s: 90, l: 30 },
    surface: { background: '48 46% 95%', foreground: '30 40% 9%', mutedForeground: '32 12% 36%', muted: '46 32% 91%', border: '44 26% 83%' },
    sidebar: 'light',
  },
  {
    id: 'white',
    name: 'Clean White',
    tagline: 'Milk-white and graphite. Calm and minimal.',
    accent: { h: 222, s: 22, l: 14 },
    onAccent: 'light',
    surface: { background: '220 20% 98%', foreground: '222 24% 9%', mutedForeground: '220 9% 40%', muted: '220 14% 95%', border: '220 13% 90%' },
    sidebar: 'light',
  },
  {
    id: 'ocean',
    name: 'Ocean Blue',
    tagline: 'Cool blue for a seafood or modern café.',
    accent: { h: 217, s: 80, l: 46 },
    onAccent: 'light',
    surface: { background: '214 34% 96%', foreground: '218 34% 10%', mutedForeground: '216 11% 38%', muted: '214 22% 93%', border: '214 20% 87%' },
    sidebar: 'light',
  },
  {
    id: 'coffee',
    name: 'Coffee Brown',
    tagline: 'Latte cream and espresso brown, made for cafés.',
    accent: { h: 24, s: 52, l: 30 },
    onAccent: 'light',
    surface: { background: '32 30% 95%', foreground: '24 32% 10%', mutedForeground: '26 11% 36%', muted: '30 22% 91%', border: '30 18% 83%' },
    sidebar: 'light',
  },
  {
    id: 'rose',
    name: 'Rose Pink',
    tagline: 'Sweet-shop and bakery pink.',
    accent: { h: 336, s: 76, l: 44 },
    onAccent: 'light',
    surface: { background: '340 32% 97%', foreground: '336 22% 10%', mutedForeground: '336 8% 40%', muted: '340 18% 94%', border: '340 15% 89%' },
    sidebar: 'light',
  },
  {
    id: 'violet',
    name: 'Royal Purple',
    tagline: 'Deep purple, close to the Digital Target brand.',
    accent: { h: 271, s: 70, l: 38 },
    onAccent: 'light',
    surface: { background: '266 32% 97%', foreground: '268 28% 10%', mutedForeground: '266 9% 40%', muted: '266 18% 94%', border: '266 15% 89%' },
    sidebar: 'light',
  },
  {
    id: 'teal',
    name: 'Mint Teal',
    tagline: 'Fresh teal, light and clean.',
    accent: { h: 176, s: 70, l: 29 },
    onAccent: 'light',
    surface: { background: '176 28% 96%', foreground: '180 28% 9%', mutedForeground: '180 8% 38%', muted: '176 15% 93%', border: '176 13% 86%' },
    sidebar: 'light',
  },
  {
    id: 'charcoal',
    name: 'Charcoal Orange',
    tagline: 'Dark charcoal sidebar with the orange accent.',
    accent: { h: 16, s: 88, l: 44 },
    onAccent: 'light',
    accentText: { h: 16, s: 88, l: 41 },
    surface: { background: '40 18% 96%', foreground: '24 15% 11%', mutedForeground: '25 8% 40%', muted: '36 14% 94%', border: '35 14% 89%' },
    sidebar: 'dark',
    sidebarColor: '24 15% 11%',
  },
  {
    id: 'navy',
    name: 'Navy Night',
    tagline: 'Deep navy sidebar with a bright blue accent.',
    accent: { h: 217, s: 80, l: 46 },
    onAccent: 'light',
    surface: { background: '214 34% 96%', foreground: '218 34% 10%', mutedForeground: '216 11% 38%', muted: '214 22% 93%', border: '214 20% 87%' },
    sidebar: 'dark',
    sidebarColor: '222 40% 12%',
  },
];

// ============================================================
// DT RETAIL THEMES — the seven looks of the DT Retail design guide.
//
// A separate family from the thirteen above so nothing about them changes.
// Each is a whole look: a dark gradient sidebar, a gradient hero banner on the
// dashboard, the brand colour on the active item and the main buttons — and,
// for Black & Gold and Night, a dark page. The colours were read from the
// guide's own screenshots. src/styles/ui-tokens.css holds the same values per
// data-ui-theme; src/test/dt-retail-look.test.ts fails if the two drift.
// ============================================================
const WHITE_PANEL: Triplet = '0 0% 100%';

export const RETAIL_THEMES: UiTheme[] = [
  {
    id: 'dtr-royal', family: 'retail', name: 'Royal Purple',
    tagline: 'Digital Target signature — deep purple luxury.',
    accent: { h: 263, s: 70, l: 50 }, onAccent: 'light',
    surface: { background: '257 37% 96%', card: WHITE_PANEL, foreground: '222 47% 11%', mutedForeground: '215 16% 40%', muted: '257 25% 94%', border: '215 27% 91%' },
    sidebar: 'dark', sidebarColor: '265 83% 14%', sidebarGradient: ['265 79% 18%', '265 88% 10%'], hero: ['270 85% 21%', '259 82% 66%'],
    swatches: ['#2a0a55', '#6d28d9', '#f4f2f9', '#f5b301'],
  },
  {
    id: 'dtr-crimson', family: 'retail', name: 'Crimson Red & White',
    tagline: 'Bold red with clean white cards.',
    accent: { h: 0, s: 72, l: 51 }, onAccent: 'light',
    accentText: { h: 0, s: 72, l: 48 }, // deeper (lighter on the dark page) where the accent is text
    surface: { background: '12 33% 97%', card: WHITE_PANEL, foreground: '222 47% 11%', mutedForeground: '215 16% 40%', muted: '12 22% 94%', border: '12 18% 89%' },
    sidebar: 'dark', sidebarColor: '358 60% 8%', sidebarGradient: ['356 58% 10%', '357 64% 5%'], hero: ['0 64% 31%', '0 81% 62%'],
    swatches: ['#2b0b0d', '#dc2626', '#faf6f5', '#ffffff'],
  },
  {
    id: 'dtr-gold', family: 'retail', name: 'Black & Gold',
    tagline: 'Dark luxury with gold accents.',
    accent: { h: 43, s: 80, l: 46 }, onAccent: 'dark',
    surface: { background: '30 9% 4%', card: '45 21% 7%', foreground: '44 59% 91%', mutedForeground: '43 14% 62%', muted: '43 21% 13%', border: '43 22% 16%' },
    sidebar: 'dark', dark: true, sidebarColor: '40 20% 3%', sidebarGradient: ['0 0% 2%', '40 27% 4%'], hero: ['43 98% 19%', '46 77% 55%'],
    swatches: ['#050505', '#d4a017', '#1a1810', '#f6efdc'],
  },
  {
    id: 'dtr-emerald', family: 'retail', name: 'Emerald',
    tagline: 'Fresh green — food & grocery.',
    accent: { h: 161, s: 94, l: 30 }, onAccent: 'light',
    accentText: { h: 161, s: 94, l: 25 }, // deeper (lighter on the dark page) where the accent is text
    surface: { background: '150 30% 96%', card: WHITE_PANEL, foreground: '222 47% 11%', mutedForeground: '215 16% 40%', muted: '150 20% 93%', border: '150 18% 88%' },
    sidebar: 'dark', sidebarColor: '161 83% 9%', sidebarGradient: ['162 81% 12%', '160 80% 6%'], hero: ['164 86% 17%', '160 69% 43%'],
    swatches: ['#063a2b', '#059669', '#f2f8f5', '#ffffff'],
  },
  {
    id: 'dtr-sunset', family: 'retail', name: 'Sunset Orange',
    tagline: 'Warm, energetic and friendly.',
    accent: { h: 21, s: 90, l: 48 }, onAccent: 'light',
    accentText: { h: 21, s: 90, l: 38 }, // deeper (lighter on the dark page) where the accent is text
    surface: { background: '30 44% 96%', card: WHITE_PANEL, foreground: '222 47% 11%', mutedForeground: '215 16% 40%', muted: '28 30% 93%', border: '28 26% 88%' },
    sidebar: 'dark', sidebarColor: '17 70% 9%', sidebarGradient: ['18 67% 12%', '18 74% 6%'], hero: ['16 76% 29%', '26 94% 63%'],
    swatches: ['#34160a', '#ea580c', '#faf6f2', '#facc15'],
  },
  {
    id: 'dtr-ocean', family: 'retail', name: 'Ocean Blue',
    tagline: 'Calm, corporate and clear.',
    accent: { h: 200, s: 98, l: 39 }, onAccent: 'light',
    accentText: { h: 200, s: 98, l: 33 }, // deeper (lighter on the dark page) where the accent is text
    surface: { background: '207 47% 96%', card: WHITE_PANEL, foreground: '222 47% 11%', mutedForeground: '215 16% 40%', muted: '207 30% 93%', border: '207 25% 88%' },
    sidebar: 'dark', sidebarColor: '203 84% 12%', sidebarGradient: ['204 82% 16%', '203 87% 9%'], hero: ['202 81% 25%', '199 89% 61%'],
    swatches: ['#07304a', '#0284c7', '#f1f6fa', '#ffffff'],
  },
  {
    id: 'dtr-night', family: 'retail', name: 'Night',
    tagline: 'Dark mode for dim shops.',
    accent: { h: 258, s: 90, l: 66 }, onAccent: 'light',
    accentText: { h: 258, s: 90, l: 75 }, // deeper (lighter on the dark page) where the accent is text
    surface: { background: '223 49% 8%', card: '221 41% 12%', foreground: '220 43% 93%', mutedForeground: '215 20% 65%', muted: '219 37% 19%', border: '220 34% 23%' },
    sidebar: 'dark', dark: true, sidebarColor: '220 51% 8%', sidebarGradient: ['221 53% 6%', '222 48% 11%'], hero: ['273 84% 22%', '259 87% 67%'],
    swatches: ['#070c17', '#8b5cf6', '#0b1120', '#e6ebf5'],
  },
];

/** Every theme the picker can apply: the thirteen Modern ones, then the DT Retail seven. */
export const ALL_THEMES: UiTheme[] = [...UI_THEMES, ...RETAIL_THEMES];

export const DEFAULT_THEME_ID = 'ember';

// Themes designed in Settings → Custom (or imported from a theme file). Registered by
// lib/customTheme.ts at start-up; the built-in lists above are never changed.
let customThemes: UiTheme[] = [];

export function registerCustomThemes(list: UiTheme[]): void {
  customThemes = list.filter(t => t.custom && t.id !== DEFAULT_THEME_ID && !ALL_THEMES.some(b => b.id === t.id));
}

export function getRegisteredCustomThemes(): UiTheme[] {
  return customThemes;
}

export function findTheme(id: string | null | undefined): UiTheme {
  return ALL_THEMES.find(t => t.id === id) || customThemes.find(t => t.id === id) || UI_THEMES[0];
}

export const isThemeId = (id: unknown): id is string =>
  typeof id === 'string' && (ALL_THEMES.some(t => t.id === id) || customThemes.some(t => t.id === id));

/** True for a DT Retail theme (the look with the gradient sidebar, hero banner and motion), built in or custom. */
export const isRetailTheme = (id: unknown): boolean =>
  typeof id === 'string' && (RETAIL_THEMES.some(t => t.id === id) || customThemes.some(t => t.id === id && t.family === 'retail'));

/** True for a theme made in Settings → Custom. */
export const isCustomTheme = (id: unknown): boolean => typeof id === 'string' && customThemes.some(t => t.id === id);
